site_name: OMOP MCP Server
site_description: Model Context Protocol Server for the Observational Medical Outcomes Partnership (OMOP) Common Data Model
site_author: vvcb

theme:
  name: material
  palette:
    scheme: default
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  features:
    - content.code.copy
    - navigation.expand
    - navigation.instant
    - navigation.search.highlight
    - navigation.search.shareable
    - navigation.search.suggest
    - navigation.search.suggest.external
    - navigation.search.suggest.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.shareable
    - search.suggest
    - search.suggest.external
    - search.suggest.indexes
  nav:
    - Home: index.md
    - Installation: installation.md
    - Contributing: contributing.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
